# Apply label "feature" if head matches "feature/*"
feature:
  head: "feature/*"
  base: "main"
# Apply label "bugfix" if head matches one of "bugfix/*" or "hotfix/*"
fix:
  head: "fix/*"
  base: "main"

chore:
  head: "chore/*"
  base: "main"

stage:
  base: "stage"
