name: automerge
on:
  pull_request_review:
    branches:
      - main
    types: [submitted]
jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - name: Merge pull requests (automerge-action)
        uses: "pascalgn/automerge-action@v0.15.6"
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
          MERGE_LABELS: ""
          MERGE_METHOD: "merge"
          MERGE_COMMIT_MESSAGE: "pull-request-title"
          MERGE_FORKS: "false"
          MERGE_RETRIES: "0"
          MERGE_REQUIRED_APPROVALS: "1"
          UPDATE_LABELS: ""
