name: draft release note
on:
  pull_request:
    branches:
      - main
    types:
      - closed
jobs:
  draft-release-note:
    runs-on: ubuntu-latest
    steps:
      - name: Release drafter
        uses: release-drafter/release-drafter@v5
        with:
          config-name: .github/release-drafter-config.yml
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
